name: flutter_translate_gen
description: Statically-typed localization keys generator for flutter_translate.
version: 2.0.0
author: Florin Bratan <florin@leadcode.dev>
homepage: https://leadcode.dev
repository: https://github.com/bratan/flutter_translate_gen

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_casing: ^1.0.1
  dart_utils: ^1.0.2
  source_gen:
  build:
  code_builder:
  analyzer:
  glob: ^2.0.0
  flutter_translate_annotations:
    git: https://github.com/hendrikdruse/flutter_translate_annotations.git

dev_dependencies:
  build_runner: '>=1.7.0 <2.0.0'
